apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  labels:
    # Operator labels
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/instance: {{ .Name }}
    # usd-specific labels
    unbind/usd-type: {{ .Definition.Type | quote }}
    unbind/usd-version: {{ .Definition.Version | quote }}
    unbind/usd-category: databases
    {{- range $key, $value := .Parameters.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}

spec:
  # --- Core RS settings -------------------------------------------------------
  members: {{ .Parameters.common.replicas | default 1 }}
  type: ReplicaSet
  version: {{ .Parameters.version | default "7.0" | quote }}

  security:
    authentication:
      modes: ["SCRAM"]
      ignoreUnknownUsers: true

  users:
    - name: admin
      db: admin
      passwordSecretRef:
        name: admin-password
      roles:
        - { name: clusterAdmin,           db: admin }
        - { name: userAdminAnyDatabase,   db: admin }
      scramCredentialsSecretName: my-scram

  # --- Pod & storage overrides -----------------------------------------------
  statefulSet:
    spec:
      # PersistentVolumeClaim for each pod
      volumeClaimTemplates:
      - metadata:
          name: data-volume      
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: {{ .Parameters.common.storage | default "1Gi" }}

      # Pod template overrides
      template:
        spec:
          containers:
          - name: mongod
            resources:
              requests:
                cpu:    {{ .Parameters.common.resources.requests.cpu   | default "100m" }}
                memory: {{ .Parameters.common.resources.requests.memory| default "128Mi" }}
              limits:
                cpu:    {{ .Parameters.common.resources.limits.cpu     | default "500m" }}
                memory: {{ .Parameters.common.resources.limits.memory  | default "256Mi" }}
            {{- if .Parameters.environment }}
            env:
            {{- range $k, $v := .Parameters.environment }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            {{- end }}

  # --- Mongod runtime tweaks --------------------------------------------------
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.cacheSizeGB: 0.25
